version: "3.9"

services:
  mongo:
    image: mongo:6.0
    container_name: xflyve-mongo
    restart: always
    ports:
      - "27018:27017"
    volumes:
      - xflyve-mongo-data:/data/db
    networks:
      - xflyve-network

  backend:
    build: ./backend
    container_name: xflyve-backend
    restart: always
    ports:
      - "5001:3001"
    env_file:
      - ./backend/.env
    depends_on:
      - mongo
    networks:
      - xflyve-network

  frontend:
    build: ./xflyve-frontend
    container_name: xflyve-frontend
    restart: always
    ports:
      - "5173:80"
    networks:
      - xflyve-network

volumes:
  xflyve-mongo-data:

networks:
  xflyve-network:
    driver: bridge
